version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=dbpass
      - POSTGRES_USER=admin
      - POSTGRES_DB=dbmap

volumes:
  postgres_data: